language: node_js
node_js:
  - 7
  - 6
  - 4
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: LDLMC4bckJYgvUmlCbSyTf7pKVcqM8qgAaUuS8oZjQ+SVrnB3xvimGe2UzkC7xGjCE4kXJnI/4Zpke+bbQ1u1AOLsv0/UtYjlFcl/i1QR7KNTuAU0h/SYhyE5Qz8aSiRXRXPzasqgHWqj0h02cjSN4OVNVs5AGff/QKbu3Gq3p4XHwADxVvxLRLj9m0Nuv+MJ4haU9ApRAKIrjaE0AFJWAhb0x6E7zJ5yj5XxCuBJGMS6/PELOY7IpNzdAGawwrDvRpyAOFanAq9oC2PnyaUVs/kWgP0mIe51fcoASOgPAf0CzcNfkJPfNSlZox/X+I6usEqz1Z/F2oAiFq96NQ+bJ1+7TArWoPFwj9DY7xsRIRpPRUot0FkEMST2VeX0aofim9SHFWqPIL40nX/uRqANcr2kC/ha3W7OrUhTkdpiblKctGvZWJrMQX0mcMqH7ATmnNtHOGnUqcCeeBt3wW3zgU8/yNslUGXulmakca9F6rghZ0YCAQ2BWkZ2fOSsHqAsJj534/OqglEKuSPXIgAiLhVYUojnUHGsPCufjlYJl8/YIeVaxGvfiu762zUtcsnParRoGZQfhgLpHr8AcSUkCtPtfuJk9S5bQnKbzptXFAzhi2Ey934tmoxXSNh2+fS0yU4YzFfuuJX1xlb71OtFdkc+Oydy8Ef2Zz5fWV+Z4Q=
  on:
    tags: true
    node: 7
